# Generated by Django 5.0 on 2023-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('name_with_initials', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nic', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('position', models.CharField(max_length=256)),
                ('post', models.TextField()),
                ('qr_key', models.TextField()),
                ('special_notes', models.TextField()),
                ('teacher_grade', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=12)),
                ('enrolled_date', models.DateField()),
                ('teaching_started_date', models.DateField()),
            ],
        ),
    ]
