# Generated by Django 5.0 on 2023-12-10 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mark', '0001_initial'),
        ('Student', '0001_initial'),
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject'),
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mark.term'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
