# Generated by Django 5.0 on 2023-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('subgrade', models.CharField(max_length=2)),
                ('subjects', models.ManyToManyField(related_name='grade_subjects', to='Subject.subject')),
            ],
        ),
    ]
