# Generated by Django 5.0 on 2023-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nic', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=25)),
                ('special_notes', models.TextField()),
            ],
        ),
    ]
