# Generated by Django 5.0 on 2023-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bucket', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
                ('stream', models.CharField(choices=[('6-9', 'Junior Secondary 6-9'), ('O/L', 'Ordinary Level (10-11)'), ('A/L', 'Advanced Level(12-13)')], max_length=10)),
            ],
        ),
    ]
